Add support for 32-, 64-, 128-, 256-, 512-, 1024- bit flavours
sindresorhus/fnv1a pull request #4
Opened 2019-01-25 18:21 UTC by lunaticmonk

@sindresorhus I implemented a fix for #3 . Please let me know if I am correct. Thanks.

2019-01-25 18:43 UTC, sindresorhus commented
Read the issue again. It's mentions `BigInt`. This will also require some tests and docs changes.

2019-01-26 06:31 UTC, lunaticmonk commented
@sindresorhus I did some changes. Please review. However, `xo` is throwing linting errors like `BigInt is not defined.`, `A function with a name starting with an uppercase letter should only be used as a constructor.`. Is there a way I can ignore them by modifying some configs?

2019-01-26 07:29 UTC, sindresorhus commented
I think the 64-, 128-, 256-, 512-, 1024 versions should be a separate method: `fnv1a.bigInt()` which should accept an options-object, so `fnv1a.bigInt({bits: 128})`. The method should validate that only the allowed bit versions are supplied.

2019-01-26 09:42 UTC, lunaticmonk commented
@sindresorhus Okay, will do that. Also, don't you think 64 bit can be solved normally rather than pushing it to bigInt?

2019-01-26 09:56 UTC, sindresorhus commented
> Also, don't you think 64 bit can be solved normally rather than pushing it to bigInt?

No, and if you think that, I'm questioning whether you're up to the task to resolve this correctly.

2019-01-26 09:56 UTC, sindresorhus requested changes

2019-01-26 09:56 UTC, sindresorhus commented on index.js
> +	if (typeof (int) === Number) {
This check is not correct.

2019-01-26 09:56 UTC, sindresorhus commented on index.js
> +		hash += (hash << getBigInt('1')) + (hash << getBigInt('4')) + (hash << getBigInt('7')) + (hash << getBigInt('8')) + (hash << getBigInt('24'));
Are you sure the algorithm is exactly the same for larger numbers? Please read up on the source material: http://www.isthe.com/chongo/tech/comp/fnv/index.html#FNV-param

2019-01-26 09:56 UTC, sindresorhus commented on index.js
> +	64: 14695981039346656037,
JavaScript does not support 64-bit numbers.

2019-11-18 06:04 UTC, closed without merging